Quick broom 🧹  (#541)
* Fix compilation error in migration/benchmarking

It fails with the following error:
expected struct `VestingInfo`, found struct `frame_support::BoundedVec`

* chore: Remove unused imports and drop dead code